-- Schema v4: add registration and verification fields to users table

ALTER TABLE users ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_line1 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_line2 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS district TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS selfie_image TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sc_certificate_file TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS income_certificate_file TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS eligibility_status TEXT DEFAULT 'pending_manual_review';
ALTER TABLE users ADD COLUMN IF NOT EXISTS registration_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS salary NUMERIC;
